<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="RollerConveyor" Id="{fea9d20d-0e09-459b-a5ba-bec52b89bada}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RollerConveyor EXTENDS Conveyor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Super^();]]></ST>
    </Implementation>
    <LineIds Name="RollerConveyor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>