<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_BeltConveyors" Id="{eb206bc1-d4a6-42f3-9c9e-531ede3780e1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BeltConveyors EXTENDS FB_Chain
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_BeltConveyors">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>