<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_PostPalletizer" Id="{d145f42d-ec17-4f04-88d0-151eae25ee5d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PostPalletizer EXTENDS FB_Chain
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_PostPalletizer">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>