<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_PrePalletizer" Id="{5dff49bc-e989-4c97-b519-5d232efdac58}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PrePalletizer EXTENDS FB_Chain
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_PrePalletizer">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>