<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Visu" Id="{2c780e66-9945-423c-a677-d03b9608941b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Visu
VAR
	bStartTL1 : BOOL;
	bStartTL2 : BOOL;
	bStartTL3 : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Visu">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>