<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_Elevator" Id="{41bd1c28-57fc-4e4f-9823-dbd6c73872aa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Elevator
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Elevator">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>