<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Version" Id="{95618842-63da-482f-8530-b7fbf5f82af2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Version
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*

1.0.1.1:	Boido	020120

Version.txt replaced with Version PRG

1.0.2.2:	Boido	020120

VersionLib removed.

1.0.3.3:	Boido	090220

Bugfix in MqttClient.getNewMessage();

1.0.4.4:	Boido	240520

Date and time as String in ST_MqttLifePackage
*)]]></ST>
    </Implementation>
    <LineIds Name="Version">
      <LineId Id="9" Count="1" />
      <LineId Id="6" Count="2" />
      <LineId Id="15" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="22" Count="1" />
      <LineId Id="18" Count="0" />
      <LineId Id="29" Count="2" />
      <LineId Id="28" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>