<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Version" Id="{c0e64eec-c0cd-4b22-8e7a-7dec7d9bd2c8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Version
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
1.0.1.1:	Boido	010120

Changed naming convention for main modules.
The first 2 letters give a hint on the inheritance relationship of the FB.

1.0.2.2:	Boido	010120

Naming convention adjustments.

1.1.0.3:	Boido	010120

Every IO variable is of type BoolIn or BoolOut.
In the future when different types will be needed,
also RealIn,RealOut,IntIn,IntOut etc.. will be added.

1.1.1.4:	Boido	010120

New StepWorkerLib v:1033, naming conventions fixes and IO adjustments

1.1.2.5:	Boido	020120

Version.txt replaced with Version PRG

1.2.2.6:	Boido	040120

Further implementation of the TransferLine StepChains.

1.3.2.7:	Boido	050120

Further implementation of the TransferLine StepChains.
*)]]></ST>
    </Implementation>
    <LineIds Name="Version">
      <LineId Id="23" Count="0" />
      <LineId Id="6" Count="16" />
      <LineId Id="5" Count="0" />
      <LineId Id="26" Count="1" />
      <LineId Id="29" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="37" Count="2" />
      <LineId Id="36" Count="0" />
      <LineId Id="24" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>