<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Elevator" Id="{46ba5991-b5f9-4f5e-abab-a4ac0cc6420f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Elevator
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Elevator">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>