<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="BeltConveyor" Id="{ab6b7528-8ac8-4e7e-bc7d-2eb87e368d42}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BeltConveyor EXTENDS Conveyor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Super^();]]></ST>
    </Implementation>
    <LineIds Name="BeltConveyor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>