<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_Conveyor" Id="{b15311d8-a9f4-4077-9cec-ef51ff0c9999}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Conveyor 
VAR_INPUT
END_VAR

VAR_OUTPUT
	bStart  : BOOL;
END_VAR
VAR
	fbStart : BoolOut;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[bStart := fbStart.getValue;]]></ST>
    </Implementation>
    <Property Name="getStart" Id="{6370b0c0-d40e-456d-89ce-6f31c418ed60}">
      <Declaration><![CDATA[PROPERTY getStart : BoolOut]]></Declaration>
      <Get Name="Get" Id="{489b8359-b98c-42ae-afe2-3461bd22238e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[getStart := fbStart;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Off" Id="{f085c888-d730-4182-bd45-298546b54d73}">
      <Declaration><![CDATA[METHOD Off : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="On" Id="{5d342f49-f715-42fd-b4a3-ca7fc5d5e1e7}">
      <Declaration><![CDATA[METHOD On : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Conveyor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Conveyor.getStart.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Conveyor.Off">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Conveyor.On">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>