<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_RollerConveyor" Id="{b1585fb0-7b13-454c-bee3-cef58924ab6e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RollerConveyor EXTENDS FB_Conveyor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Super^();]]></ST>
    </Implementation>
    <LineIds Name="FB_RollerConveyor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>