<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_Cylinder" Id="{4dff6417-8bf1-4724-a444-43bb6b5867e9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Cylinder 
VAR_INPUT
END_VAR
VAR_OUTPUT
	bExtended : BOOL;
END_VAR
VAR
	bStart AT%Q* : BOOL;
	fbExtendedSignal : BoolIn;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[bExtended := fbExtendedSignal.getValue;
]]></ST>
    </Implementation>
    <LineIds Name="FB_Cylinder">
      <LineId Id="12" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>